// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesticideContext;

#nullable disable

namespace Pesticide.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PesticideContext.Pesticide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChemicalComposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChineseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignMaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetBrcodeXML")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetGropty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesticideCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevocationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("formCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pesticide");
                });

            modelBuilder.Entity("PesticideContext.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Barcode");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PesticideContext.Register", b =>
                {
                    b.Property<string>("RegtID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Permit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegtID");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("PesticideContext.ThirdParty", b =>
                {
                    b.Property<bool>("DataStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataTime")
                        .HasColumnType("datetime2");

                    b.ToTable("ThirdParty");
                });
#pragma warning restore 612, 618
        }
    }
}
